apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: MI_VARIABLE
      value: "Eder"
    - name: MI_OTRA_VARIABLE
      value: "EderMena"
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits: # Limita la cantidad de recursos para memoria y cpu para el pod
        memory: "128Mi"
        cpu: "500m"
    readinessProbe: #Es una forma de expliar a kubernetes que el pod esta listo para recibir trafico por el puerto 80
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe: #Es una forma de expliar a kubernetes que el pod esta vivo por el puerto 80
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    ports:
    - containerPort: 80